// Tests for design §9.1 config regeneration: a node's config is generated once
// and cached in settings, so a changed *generator* (the 2026-09-16 DNS format
// revision in §9.4) would never reach existing nodes without an explicit sync.
package httpapi

import (
	"strings"
	"testing"

	"github.com/fonlan/fobe/internal/server/singbox"
	"github.com/fonlan/fobe/internal/server/store"
)

func TestSyncSingboxConfigsRegeneratesStaleConfigs(t *testing.T) {
	_, api := newTestServer(t)
	nodeID, _ := seedNode(t, api, "sb", "m-sb-1", "198.51.100.9")

	// A node the panel already manages, carrying a config generated by the old
	// (address-based DNS) template. Its inbound carries the credential, which is
	// where the sync reads it from now (§10.1 实现修订 2026-09-17e) — the node
	// keeps serving the password its clients already hold.
	const stale = `{"dns":{"servers":[{"tag":"local-dns","address":"local"}]},
	  "inbounds":[{"type":"anytls","listen_port":22039,"users":[{"name":"default","password":"shared-pw"}]}]}`
	if err := api.Store.SetSetting("singbox_config:"+nodeID, stale, false); err != nil {
		t.Fatal(err)
	}
	if err := api.Store.UpsertNodeSingbox(&store.NodeSingbox{
		NodeID: nodeID, DesiredVersion: "1.15.0-alpha.4", Port: 22039,
		ConfigHash: singbox.ConfigHash([]byte(stale)), Status: "degraded",
	}); err != nil {
		t.Fatal(err)
	}

	if n := api.SyncSingboxConfigs(); n != 1 {
		t.Fatalf("sync updated %d nodes, want 1", n)
	}

	stored, err := api.Store.GetSetting("singbox_config:" + nodeID)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(stored, `"address"`) {
		t.Fatalf("stale legacy config survived the sync: %s", stored)
	}
	want, err := singbox.BuildNodeConfig(22039, "shared-pw")
	if err != nil {
		t.Fatal(err)
	}
	if stored != string(want) {
		t.Fatalf("synced config differs from the current template:\n got %s\nwant %s", stored, want)
	}
	sb, err := api.Store.GetNodeSingbox(nodeID)
	if err != nil {
		t.Fatal(err)
	}
	if sb.ConfigHash != singbox.ConfigHash(want) {
		t.Fatalf("config_hash not refreshed: %s", sb.ConfigHash)
	}
	// The desired half is preserved: only the config bytes move.
	if sb.DesiredVersion != "1.15.0-alpha.4" || sb.Port != 22039 {
		t.Fatalf("desired state clobbered: %+v", sb)
	}

	// Idempotent: a second pass finds nothing to do.
	if n := api.SyncSingboxConfigs(); n != 0 {
		t.Fatalf("second sync updated %d nodes, want 0", n)
	}
}

// Nodes the panel does not manage (no desired_version) are left alone.
func TestSyncSingboxConfigsSkipsUnmanagedAndUnconfigured(t *testing.T) {
	_, api := newTestServer(t)
	nodeID, _ := seedNode(t, api, "idle", "m-idle-1", "198.51.100.10")
	if err := api.Store.SetSetting("singbox_config:"+nodeID, "{}", false); err != nil {
		t.Fatal(err)
	}
	if n := api.SyncSingboxConfigs(); n != 0 {
		t.Fatalf("sync touched %d nodes without a credential, want 0", n)
	}
	// §10.1 实现修订 2026-09-17e: nothing global is minted any more, and an
	// unmanaged node is not demand either way.
	if _, err := api.Store.GetSetting("anytls_password"); err == nil {
		t.Fatal("an unmanaged node minted a global anytls password")
	}

	if n := api.SyncSingboxConfigs(); n != 0 {
		t.Fatalf("sync touched %d unmanaged nodes, want 0", n)
	}
	if stored, _ := api.Store.GetSetting("singbox_config:" + nodeID); stored != "{}" {
		t.Fatalf("unmanaged node's setting was rewritten: %s", stored)
	}
}

// §10.1 实现修订 2026-09-17e: the sync never mints. A managed node whose config
// carries no readable credential is a node whose password we do not know — the
// probe may well be serving one — so it is skipped with a warning instead of
// being rewritten with a credential no client has.
func TestSyncSingboxConfigsSkipsNodesWithoutACredential(t *testing.T) {
	_, api := newTestServer(t)
	nodeID, _ := seedNode(t, api, "sb", "m-sync-mint", "198.51.100.11")
	if err := api.Store.UpsertNodeSingbox(&store.NodeSingbox{
		NodeID: nodeID, DesiredVersion: "1.15.0-alpha.4", Port: 22040, Status: "running",
	}); err != nil {
		t.Fatal(err)
	}

	if n := api.SyncSingboxConfigs(); n != 0 {
		t.Fatalf("sync updated %d nodes that have no credential, want 0", n)
	}
	if _, err := api.Store.GetSetting("singbox_config:" + nodeID); err == nil {
		t.Fatal("the sync wrote a config for a node whose credential it cannot know")
	}
	if _, err := api.Store.GetSetting("anytls_password"); err == nil {
		t.Fatal("the sync minted a global anytls password")
	}
}
